name: todoapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  bloc: ^8.1.4
  flutter_bloc: ^8.1.5
  json_annotation: ^4.8.1
  json_serializer: ^0.2.0
  freezed: ^2.4.7
  freezed_annotation: ^2.4.1
  firebase_core: ^2.27.0
  cloud_firestore: ^4.15.8
  firebase_auth: ^4.17.8
  go_router: ^13.2.2
  get_it: ^7.6.7
  flutter_layout_grid: ^2.0.6
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.9
  json_serializable: ^6.7.1

flutter:

  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/svgs/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
    - family: TimesNewRoman
      fonts:
        - asset: assets/fonts/TimesNewRoman.ttf
